name: Никита Махов
description: Фронтенд-разработка, игры и машины
meta_description: "Никита Махов, Фронтенд-разработка, игры, машины"

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 5
baseurl: /
domain_name: 'http://defite.github.io'
#google_analytics: 'UA-XXXXXXXX-X'
disqus: false
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'http://defite.github.io'
author:         'Никита Махов'
authorTwitter:  'life_maniac'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
